Fixed parsing error in 2026-05-20-why-im-betting-on-a-saas-rally-in-2026.md
Double-quotes around "software" broke parsing.

Error: YAML Exception reading /srv/jekyll/_posts/2026-05-20-why-im-betting-on-a-saas-rally-in-2026.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1